[credentials]
  [credentials.usernames.ME]
  email = "vincent.giraud@tpicap.com"
  name = "cmwa"
  password = "$2b$12$XXIQ9tAncUi5M3ivIyMNVuOsjRRd/Wih8N4kqvFmR4Y172NOe7UkC"

  [credentials.usernames.Maxence]
  email = "maxence.lenoir@tpicap.com"
  name = "Maxence"
  password = "$2b$12$5ANFn1OulbSOMOy1.sFhKe/Worv0LJgrms6FX24vYfBPFLnNvlIU."

  [credentials.usernames.ThomasH]
  email = "thomas.helaine@tpicap.com"
  name = "Thomas"
  password = "$2b$12$aq/LsGY2pZcB4ntRA5OyTueVPEq2N4lxQAn1mHotwzzJtb8G7fuWS"

  [credentials.usernames.Louis]
  email = "louis.barranger@tpicap.com"
  name = "Louis"
  password = "$2b$12$cLVr93ki2h0oP/c0KGtslePmVGZR7ilxwzPavzy6iNU/hUAhIXWqG"

  [credentials.usernames.Maxime]
  email = "Maxime.Aboujdid@tpicap.com"
  name = "Maxime"
  password = "$2b$12$Rm/h9PEOaehygBjtmFRFXui0/zCN50C5L4MgQISqqIlRIU2X8wvaa"

  [credentials.usernames.Alice]
  email = "Alice.Ayme@tpicap.com"
  name = "Alice"
  password = "$2b$12$ZpTorGMajJNxb8Q8mq3vCOyOlSjS1Nvgs/NPIpHDkR2ZnvjsPWI2q"

  [credentials.usernames.Sami]
  email = "Sami.Benjelloun@tpicap.com"
  name = "Sami"
  password = "$2b$12$MLC3OGdP26Elmwf7qWBpV.PfXYn9OKdE899xK0.P.vROJBNEsNERu"

  [credentials.usernames.Matthieu]
  email = "Matthieu.Bonnet@tpicap.com"
  name = "Matthieu"
  password = "$2b$12$XuXtKzOSt0ifGY3EjvNsX.ELlE7NF7a0p/MEWTVPtaA4mnEmMI7cm"

  [credentials.usernames.Kevin]
  email = "Kevin.Bruno@tpicap.com"
  name = "Kévin"
  password = "$2b$12$XcIarae9RwCdfdBcB4QDruzomcagAhDVO.ANmXf9SwfNyUL9jMtlm"

  [credentials.usernames.Alexandre]
  email = "Alexandre.Carvalho@tpicap.com"
  name = "Alexandre"
  password = "$2b$12$h3fikuLjGkKhJt/OPUjVAOx57qb.ohMk2cnM8sZeTegHbUOegyHj."

  [credentials.usernames.Eric]
  email = "Eric.Choisy@tpicap.com"
  name = "Eric"
  password = "$2b$12$4PwpA/7/1PPo3Qj1jg9KmeaTes7u8icN/QXOtS000SEnQTRaYSagC"

  [credentials.usernames.Corentin]
  email = "Corentin.Marty@tpicap.com"
  name = "Corentin"
  password = "$2b$12$J5vph06ZP98kOtSxx.OkROy6j1pj3USXAtyO7wxX3qQz1uLo97gsi"

  [credentials.usernames.Michele]
  email = "Michele.Mombelli@tpicap.com"
  name = "Michele"
  password = "$2b$12$dIX0CGUG7YVMpwf4eOYah.jUic69MVqgYt13s4yqmUK0ORTuY7KCC"

  [credentials.usernames.Veneta]
  email = "Veneta.Nikolova@tpicap.com"
  name = "Veneta"
  password = "$2b$12$wvXycR9DrA0sgjInJtcRyOx.0gKvKOqeDQWto2PmWCfy0WwhFe8r6"

  [credentials.usernames.Alessio]
  email = "Alessio.Olmi@tpicap.com"
  name = "Alessio"
  password = "$2b$12$xpZr5iuo5o4/KL1jaObx9uvbHrBDUt6OKo1gUbLVSaKg8GQ7iGm5y"

  [credentials.usernames.Mathias]
  email = "mathias.paladino@tpicap.com"
  name = "Mathias"
  password = "$2b$12$CtcXSTuDGjE64LRKVDUds.ZYUyd/9pcyMkIVXIGObnBq/syiqBgOO"

  [credentials.usernames.CharlesL]
  email = "Charles-Louis.Planade@tpicap.com"
  name = "Charles-Louis"
  password = "$2b$12$usBi/LyybgaNvvI2EHDx6.NZ7QIekjCLneMBcn9ZEAQ1NOz5BCpG6"

  [credentials.usernames.Chloe]
  email = "Chloe.Rondelet@tpicap.com"
  name = "Chloé"
  password = "$2b$12$FF/NUbLNSQN3rAeuzmlwGuJ95cbC8O3iWzCgix72nAL8sQgYpVWU2"

  [credentials.usernames.PierreJ]
  email = "Pierre-Jean.Roudergue@tpicap.com"
  name = "Pierre-Jean"
  password = "$2b$12$jRcur0mQAd7vblyIGHqxAOZ86K8AfS6nTL0F7WCAWo3YQK6oztjOe"

  [credentials.usernames.ThomasS]
  email = "Thomas.Schemba@tpicap.com"
  name = "Thomas"
  password = "$2b$12$/0/ww/qozpvlPEgvw3WlvuXM0Sr6rxoFFEaFDODz1Y/Ji0MQKT2YG"

  [credentials.usernames.JeanP]
  email = "Jean-Pierre.Tabart@tpicap.com"
  name = "Jean-Pierre"
  password = "$2b$12$S2RNTG12ssFV6ULt0SVLtuIF15V2XokQLtBflZ1h7FWGLoE.hHcei"

  [credentials.usernames.Sarah]
  email = "Sarah.Thirion@tpicap.com"
  name = "Sarah"
  password = "$2b$12$vNvLnXxApXIhjEK7D3smPO2V2WOd48oHykdkx03Izht4G6WXeZIb6"

  [credentials.usernames.Julien]
  email = "Julien.Thomas@tpicap.com"
  name = "Julien"
  password = "$2b$12$DrUfC415.a0F1FtEkuPiY.MqZOGim7lE08A3tcu/bAm5nvr9l5.QO"

  [credentials.usernames.Florent]
  email = "Florent.Thy-Tine@tpicap.com"
  name = "Florent"
  password = "$2b$12$/6FoXD5rZpoKg990NbqrMeOzythPzZZYm3GpzlixdDu8AwFTd4rp6"

  [credentials.usernames.Lucille]
  email = "Lucille.Fettu@tpicap.com"
  name = "Lucille"
  password = "$2b$12$jmB.vV/4RD/yHTtmq5aUQOPhZ1dwGB.Rs27L3EnGM4keLCIC3NCpm"

[cookie]
expiry_days = 30
key = "crm_app_auth_key"
name = "crm_app_auth"

[supabase]
url = "https://mrmzvytjexywnphyjjmd.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ybXp2eXRqZXh5d25waHlqam1kIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzYxMDY1NywiZXhwIjoyMDgzMTg2NjU3fQ.FkQxhhsFb9_5pq9Ws5N4Fx09ZWBROzNfSPCV4T1E8nE"